### ISSUE TITLE
Switch to using Redux Toolkit for store setup and Redux logic

### ISSUE THREAD

**Issue by markerikson** [sidetrade-labs/react-redux-typescript#1] opened 2020-02-21 23:48 UTC
Hi, I'm a Redux maintainer.

I’d specifically like to recommend that you use our new Redux Toolkit package, which is now our recommended approach for writing Redux logic. It includes utilities to simplify several common Redux use cases, including store setup, defining reducers, immutable update logic, and even creating entire “slices” of state at once:

https://redux-toolkit.js.org

It's already written in TypeScript, and the API is designed to minimize the amount of type declarations you'll have to add by hand.

Please let me know if you've got any questions on using it!

**Comment by deonclem** [comment] 2020-02-23 17:19
Hi Mark!

This looks really cool! I was not aware such a tool existed when I did my research. Will look into it and add it to the repo as soon as I can.

**Comment by markerikson** [comment] 2020-02-23 17:54
Yeah, it's been out in some form for about a year and a half, but we only put out 1.0 last fall (and renamed it from "Redux Starter Kit" to "Redux Toolkit" to remove confusion about its purpose):

https://blog.isquaredsoftware.com/2019/10/redux-starter-kit-1.0/

**Comment by deonclem** [comment] 2020-02-25 18:57
Works great, documentation was very clear.

One single question:

Is there a way for a reducer to accept a conditional payload?

For instance, from:
```typescript
reducers: {
    search: (state, action) => {
      ....
    }
  }
```
I would like to call `search` with and without params.

Calling `dispatch(search())` gives the error:

```text
(alias) search<ISearchQuery>(payload: ISearchQuery): {
    payload: ISearchQuery;
    type: string;
} (+1 overload)
import search

Calling this {@link redux#ActionCreator} with an argument will return a {@link PayloadAction} of type T with a payload of P If possible, P will be narrowed down to the exact type of the payload argument.

Expected 1 arguments, but got 0.ts(2554)
typings.d.ts(99, 20): An argument for 'payload' was not provided.
```

Calling `search({})` works as intended but feels a bit off.

Anything I've missed?

**Comment by markerikson** [comment] 2020-02-25 19:00
When using TS, all case reducers should declare the expected action type as `(state, action: PayloadAction<SomePayloadType>)`.  

In this case, what you probably want is:

```ts
search(state, action: PayloadAction(ISearchQuery | undefined) {}
```

Related issue:

https://github.com/reduxjs/redux-toolkit/issues/370

**Comment by deonclem** [comment] 2020-02-25 19:14
I feel dumb now 😄 

Thanks a lot! 

Closing as fixed in https://github.com/sidetrade-labs/react-redux-typescript/pull/2

**Closed as completed by deonclem** 2020-02-25 19:14 UTC

**Comment by markerikson** [comment] 2020-02-25 19:17
Yeah, I actually noticed yesterday that our "Usage with TS" guide page doesn't clearly spell that out.  I need to update it accordingly.

**Comment by markerikson** [comment] 2020-02-25 19:23
I actually see some issues with the PR (after you'd merged it, I know). Went ahead and left some review comments over there.
